name = "fuika_game"
version = "0.1.0"
license = "license"
author = "Jonas Müller"
maintainer = "jonmue@uni-bremen.de"
copyright = "Copyright 2024, Jonas Müller"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
fortran-raylib = { git = "https://github.com/interkosmos/fortran-raylib.git" }

